[package]
name = "sm3"
version = "0.4.2"
description = "SM3 (OSCCA GM/T 0004-2012) hash function"
readme = "README.md"

[dependencies]
digest = "0.10.7"

[dev-dependencies]
digest = { version = "0.10.7", features = ["dev"] }
hex-literal = "0.2.2"

[features]
default = ["std"]
std = ["digest/std"]
